server:
  port: ${SERVER_PORT:9091}
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

camunda:
  bpm:
    authorization:
      enabled: true
    webapp:
      security:
        enabled: false
    database:
      schema-name: camunda
      table-prefix: camunda.
      schema-update: true
    admin-user:
      id: ${CAMUNDA_ADMIN_ID}
      password: ${CAMUNDA_ADMIN_PASSWORD}
      first-name: ${CAMUNDA_ADMIN_FIRST_NAME}
    history-level: full

security:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl-minutes: 5
    refresh-ttl-days: 7

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
    org.springframework.security: DEBUG

frontend:
  url: https://localhost:5174
